[hugoVersion]
extended = true
min = "0.95.0"

[[mounts]]
source = "assets"
target = "assets"

[[mounts]]
source = "data"
target = "data"

[[mounts]]
source = "i18n"
target = "i18n"

[[mounts]]
source = "layouts"
target = "layouts"

[[mounts]]
source = "static"
target = "static"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/davidsneighbour/hugo-hooks"
